"""Initial schema and row-level security.

The tables are created from the model metadata rather than being restated as
several hundred lines of ``op.create_table`` — for a first revision the models
*are* the specification, and restating them by hand only creates a second
version to drift. Every revision after this one is a normal autogenerated
diff against that same metadata.

The one thing metadata cannot express is row-level security, so that is
applied explicitly: it is what makes cross-tenant reads impossible rather than
merely unlikely.

Creating the database, the application role and any extensions needs
privileges a migration should not assume. Those live in
``scripts/bootstrap.sql``, run once by a superuser before this migration.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-08
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()

    # ── Tables ─────────────────────────────────────────────────────────────
    from app.db.base import Base
    import app.models  # noqa: F401  (registers every mapper)

    Base.metadata.create_all(bind=bind)

    # ── Row-level security ─────────────────────────────────────────────────
    # Every tenant-scoped table gets FORCE ROW LEVEL SECURITY plus a policy
    # keyed on the `app.current_tenant` setting each session pins.
    from app.db.rls import apply_policies

    apply_policies(bind)


def downgrade() -> None:
    bind = op.get_bind()

    from app.db.rls import drop_policies

    drop_policies(bind)

    from app.db.base import Base
    import app.models  # noqa: F401

    Base.metadata.drop_all(bind=bind)
